-- the autogenerated indices for these will start at 5
INSERT INTO provider (name, base_url, disabled, deprecated, api_key_env_var, created_dt) VALUES 
    ('xAI', 'https://api.x.ai/v1', 0, 0, 'XAI_API_KEY', strftime('%s', 'now')),
    ('Perplexity', 'https://api.perplexity.ai', 0, 0, 'SONAR_API_KEY', strftime('%s', 'now'));

-- Insert models using subqueries to get provider IDs by name (robust to autoincrement changes)
INSERT INTO model (provider_id, model, api_type, disabled, deprecated, created_dt) VALUES 
    ((SELECT id FROM provider WHERE name = 'xAI'), 'grok-4-0709', 0, 0, 0, strftime('%s', 'now')),
    ((SELECT id FROM provider WHERE name = 'xAI'), 'grok-4-fast-non-reasoning', 0, 0, 0, strftime('%s', 'now')),
    ((SELECT id FROM provider WHERE name = 'xAI'), 'grok-4-fast-reasoning', 0, 0, 0, strftime('%s', 'now')),
    ((SELECT id FROM provider WHERE name = 'xAI'), 'grok-code-fast-1', 0, 0, 0, strftime('%s', 'now')),
    ((SELECT id FROM provider WHERE name = 'Perplexity'), 'sonar', 0, 0, 0, strftime('%s', 'now')),
    ((SELECT id FROM provider WHERE name = 'Perplexity'), 'sonar-pro', 0, 0, 0, strftime('%s', 'now')),
    ((SELECT id FROM provider WHERE name = 'Perplexity'), 'sonar-reasoning', 0, 0, 0, strftime('%s', 'now')),
    ((SELECT id FROM provider WHERE name = 'Perplexity'), 'sonar-reasoning-pro', 0, 0, 0, strftime('%s', 'now'));